Composeライブラリの導入
Ryokusa/yumemi-droid-training pull request #38
Opened 2023-08-21 07:54 UTC by Ryokusa

## 修正内容
Resolve #10

- 依存関係にJetpack Compose追加
- メイン画面をCompose化

## レビューレベルの設定

- [ ] まったく見ないでApproveする(基本的には非推奨。)
- [x] ぱっとみて違和感がないかチェックしてApproveする
- [ ] 仕様レベルまで理解して、仕様通りに動くかある程度検証、動作確認までしてApproveする
- [ ] その他 (以下にコメント記載)

## レビュー観点
特になし

2023-08-21 08:05 UTC, tmk815 requested changes
基本的には問題ありませんでした！
bomのバージョンだけ確認お願いします〜

2023-08-21 08:05 UTC, tmk815 commented on app/build.gradle.kts
> +    val composeBom = platform("androidx.compose:compose-bom:2023.01.00")
![must-badge](https://img.shields.io/badge/review-must-red.svg)
特に理由がなければ最新のbomは`2023.08.00`なのでそちらを使ってください！
[日本語版](https://developer.android.com/jetpack/compose/bom/bom?hl=ja)のページ古いことが多々あるのでバージョン参照する場合は言語を変えて[英語版](https://developer.android.com/jetpack/compose/bom)でも確認するのが（めんどくさいですが）おすすめです😢

https://developer.android.com/jetpack/compose/bom/bom-mapping

2023-08-21 08:06 UTC, tmk815 commented on app/build.gradle.kts
> +    implementation("androidx.activity:activity-compose:1.6.1")
こちらも特に意図して1.6.1を選んだわけでなければ上げてしまってよさそうです

2023-08-22 05:13 UTC, Ryokusa commented on app/build.gradle.kts
> +    implementation("androidx.activity:activity-compose:1.6.1")
バージョンアップいたしました
https://github.com/Ryokusa/yumemi-droid-training/pull/38/commits/4e5f688baf2bc1f4e241ed76fa9e580c46b58321

2023-08-22 05:13 UTC, Ryokusa commented on app/build.gradle.kts
> +    implementation("androidx.activity:activity-compose:1.6.1")
4e5f688baf2bc1f4e241ed76fa9e580c46b58321

2023-08-22 05:15 UTC, Ryokusa commented on app/build.gradle.kts
> +    implementation("androidx.activity:activity-compose:1.6.1")
bomバージョンアップにともない、gradle, kotlin, compose compilerもバージョンアップいたしました
gradle：　0260ae601143227477600144279ead417e5149fe　
kotlin, compose compiler：　61653796f697c2139f0ab2183e7680f7a82c7d0c

2023-08-22 05:16 UTC, Ryokusa commented on app/build.gradle.kts
> +        kotlinCompilerExtensionVersion = "1.3.2"
バージョンアップいたしました
https://github.com/Ryokusa/yumemi-droid-training/pull/38/commits/4e5f688baf2bc1f4e241ed76fa9e580c46b58321

2023-08-22 05:16 UTC, Ryokusa commented on app/build.gradle.kts
> +    val composeBom = platform("androidx.compose:compose-bom:2023.01.00")
バージョンアップいたしました
https://github.com/Ryokusa/yumemi-droid-training/pull/38/commits/4e5f688baf2bc1f4e241ed76fa9e580c46b58321

2023-08-22 05:18 UTC, Ryokusa commented on app/build.gradle.kts
> +    val composeBom = platform("androidx.compose:compose-bom:2023.01.00")
bomバージョンアップに伴い、gradle, kotlin等バージョンアップしています
0260ae601143227477600144279ead417e5149fe
61653796f697c2139f0ab2183e7680f7a82c7d0c

2023-08-22 05:19 UTC, Ryokusa commented on app/build.gradle.kts
> +    implementation("androidx.activity:activity-compose:1.6.1")
バージョンアップいたしました
4e5f688baf2bc1f4e241ed76fa9e580c46b58321

2023-08-22 05:20 UTC, Ryokusa commented on app/build.gradle.kts
> +    val composeBom = platform("androidx.compose:compose-bom:2023.01.00")
また、bom2023.08.00がsdk34を使用したライブラリが含まれているため、compile sdk versionもアップしています
09c1481f675ace64f769cd8f8f47bd03e1ae94fa

2023-08-22 05:21 UTC, Ryokusa commented
JDKが17ではなく11であるためにLintエラーが起こっている模様

2023-08-22 05:23 UTC, Ryokusa commented
その他依存関係をバージョンアップしました
https://github.com/Ryokusa/yumemi-droid-training/pull/38/commits/2644c084714f5326dc29a040be67122923829736

2023-08-22 06:53 UTC, tmk815 approved these changes
LGTMです✅

2023-08-22 06:53 UTC, Ryokusa commented
moshiのバージョンによってビルドエラーが起きたので修正
https://stackoverflow.com/questions/67410992/upgrading-android-kotlin-version-to-1-5-0-throwing-error-message-on-build

2023-08-22 06:54 UTC, merged