Feature/14
Ryokusa/yumemi-droid-training pull request #46
Opened 2023-08-29 07:41 UTC by Ryokusa

## 修正内容
Resolve #14

## レビューレベルの設定

- [ ] まったく見ないでApproveする(基本的には非推奨。)
- [ ] ぱっとみて違和感がないかチェックしてApproveする
- [x] 仕様レベルまで理解して、仕様通りに動くかある程度検証、動作確認までしてApproveする
- [ ] その他 (以下にコメント記載)

## レビュー観点
- プログラムをできるだけわかりやすく分割したつもりですが、わかりにくい・冗長なところがあればお願いします

## スクリーンショット
<img src="https://github.com/Ryokusa/yumemi-droid-training/assets/57885690/6d10b2ad-dcb1-4df3-805a-71b45abf3520" height=400></img>

## 備考
- 初期値例外時の処理についての記述がないので、初期値は例外を出さないという前提で実装しています

2023-08-29 08:14 UTC, tmk815 requested changes
いくつかコメントさせていただきました！
追加の要件になって申し訳ないですが、いい機会なので画面回転周りの対応もお願いします🙆

2023-08-29 08:14 UTC, tmk815 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherApp.kt
> +    var showErrorDialog: Boolean by remember {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
(要件には無いですがConfiguration Change後でも状態を保持する学習のいい機会なので)画面回転でダイアログが閉じないよう対策お願いします！

2023-08-29 08:14 UTC, tmk815 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherApp.kt
>      var weatherInfoData by remember {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
(こちらも要件には無いですが)画面回転で天気の内容が書き変わるので対策お願いします！

2023-08-29 08:14 UTC, tmk815 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherFetchErrorDialog.kt
> +            title = { Text(text = "Errorエラー") },
![must-badge](https://img.shields.io/badge/review-must-red.svg)
#14 の内容に合わせて`Error`に修正お願いします。

2023-08-29 08:14 UTC, tmk815 commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherFetchErrorDialog.kt
> +                Text("CANCEL")
![must-badge](https://img.shields.io/badge/review-must-red.svg)
#14 の内容に合わせて`Close`に修正お願いします。

2023-09-02 07:30 UTC, Ryokusa commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherFetchErrorDialog.kt
> +            title = { Text(text = "Errorエラー") },
修正しました
https://github.com/Ryokusa/yumemi-droid-training/pull/46/commits/46ac7430251fb7aa32a4dc2b93e256fa3756d4ea

2023-09-02 07:30 UTC, Ryokusa commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherFetchErrorDialog.kt
> +                Text("CANCEL")
修正しました
https://github.com/Ryokusa/yumemi-droid-training/pull/46/commits/46ac7430251fb7aa32a4dc2b93e256fa3756d4ea

2023-09-02 07:30 UTC, Ryokusa commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherApp.kt
>      var weatherInfoData by remember {
rememberSavableで保持するよう修正しました
https://github.com/Ryokusa/yumemi-droid-training/pull/46/commits/67ede20bb67e09c9af804b87bd1076d61907bc80

2023-09-02 07:31 UTC, Ryokusa commented on app/src/main/java/jp/co/yumemi/droidtraining/components/WeatherApp.kt
> +    var showErrorDialog: Boolean by remember {
dialog状態をrememberSavableで保持するよう修正しました
https://github.com/Ryokusa/yumemi-droid-training/pull/46/commits/67ede20bb67e09c9af804b87bd1076d61907bc80

2023-09-04 00:19 UTC, tmk815 approved these changes
LGTMです✅

2023-09-04 07:10 UTC, merged